### ISSUE TITLE
vm is missing disks

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#165]
When importing VM second time (meaning DV and PVC already exists) the import completes immediately, but the VM is created without any disks

1. The VMs shouldn't point to the same DV/PVC as one might do some changes on one and then decide to import the VM in previous state from oVirt
2. would be good to add VM name to the DV and append random string (generateName)  to the DV/PVC

**Comment by pkliczewski** [comment]
The question is whether we should allow to import the same vm more than once.

**Comment by mtessun** [comment]
I think we typically should detect that gracefully and give the option to re-import (we could also put a message that the customer must clean up from the previous import and not do it automatically).

But I believe importing the same VM more than once is not sensible and might lead to issues later (assume the VM has fixed IP addresses and two or more instances of it are started, etc.).

In case the customer really wants to import the VM more than once he can still change the name, disk-names, etc. to have a new "unique" VM (still I would not advise doing so).

**Comment by pkliczewski** [comment]
As @suomiy suggested the issue is related to reuse of disk attachment id as a name [here](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/providers/ovirt/mapper/mapper.go#L254). We need to use `generateName`.

**Comment by masayag** [comment]
Instead of using generate-name, I'll create the dv-name based on target-vm-name + "-" + disk-attachment-id.

target-vm-name should be unique in each namespace which assure that the dv name will be unique as well combined with the disk-attachment-id. The name will be normalize to match names restrictions.

The reasons I'd prefer to avoid using GenerateName in this context are:
1. Have VM notation as part of DV name (could have been achieved as a prefix to the GenerateName)
2. Preserve the origin disk-id (could have been achieved by adding annotation with its value)
3. The current code relies on the existence of DV-name prior to its creation for various logic. Since we are able to achieve the uniqueness without using the GenerateName we can reduce significantly the required changes.
