### ISSUE TITLE
Replicate PCI layout for disks and NICs

### ISSUE THREAD

**Issue by ghost** [kubevirt/vm-import-operator#173]
When migrating a virtual machine, the PCI layout is not preserved. This can lead the operating system to not recognize the device. For example, a NIC name under Linux is dependent on its PCI address. The [`Interface` struct](https://github.com/kubevirt/client-go/blob/4cc1d98fcf5591c7c95faac894262284463a5664/api/v1/schema.go#L943) and the [`Disk` struct](https://github.com/kubevirt/client-go/blob/4cc1d98fcf5591c7c95faac894262284463a5664/api/v1/schema.go#L412) allow specifying the PCI address, via the `PciAddress` attribute.

It would be valuable to allow keeping the source PCI addresses whenever possible. This could be a `VirtualMachineImportSpec` optional boolean field.

**Comment by pkliczewski** [comment]
At the moment we block nic passthrough [here](https://github.com/kubevirt/vm-import-operator/blob/c8ad434ed738a0d77d11398e0589e8ec90b875df/pkg/providers/ovirt/validation/validators/nic-validator.go#L104). The same story is for disks [here](https://github.com/kubevirt/vm-import-operator/blob/c8ad434ed738a0d77d11398e0589e8ec90b875df/pkg/providers/ovirt/validation/validators/storage-validator.go#L179). Marking this one as enhancement.

**Comment by ghost** [comment]
Oh, `PciAddress` is for PCI Passthrough? I thought it was the virtual PCI address of the device in the guest definition, i.e. the libvirt XML file. My requirement is to keep the same virtual PCI addresses as in VMware.

**Comment by pkliczewski** [comment]
I had a chat with Michal S. about it since I was not able to find how to get this information from the [api](http://ovirt.github.io/ovirt-engine-api-model/master/) and @masayag checked the engine implementation. Apparently we are not able to get vm devices from oVirt/RHV so with that I do not think we can fix this.

**Comment by michalskrivanek** [comment]
it doesn't make sense for i440fx -> q35 conversions because it changes too much. And for q35->q35...perhaps only if cnv would accomodate the little details and differences in the VMs and just run RHV VMs unmodified. In that case, though, we could as well support live migration! So maybe worth considering

Also, we don't really have guest addresses in API. That would need to be added, which is not really a problem. Depends if it would need to be per RHV device or rather "everything" as RHV doesn't track all the devices, just those which it cares about. But if you want to put tthings in the same places you may need to know the full topology

**Comment by pkliczewski** [comment]
@fdupont-redhat Do you think we should open ovirt/rhv RFE to add vm devices support to the api?

**Comment by pkliczewski** [comment]
Created BZ: https://bugzilla.redhat.com/1848456

**Comment by ahadas** [comment]
> it doesn't make sense for i440fx -> q35 conversions because it changes too much. And for q35->q35...perhaps only if cnv would accomodate the little details and differences in the VMs and just run RHV VMs unmodified. In that case, though, we could as well support live migration! So maybe worth considering

+1
 
> Also, we don't really have guest addresses in API. That would need to be added, which is not really a problem. Depends if it would need to be per RHV device or rather "everything" as RHV doesn't track all the devices, just those which it cares about. But if you want to put tthings in the same places you may need to know the full topology

As discussed on [bz 1848456](https://bugzilla.redhat.com/show_bug.cgi?id=1848456), it will be way easier to let the client fetch the complete OVF and retrieve the PCI addresses from it

/CC @liranr23
