### ISSUE TITLE
Don't use TemplateV1Client

### ISSUE THREAD

**Issue by jakub-dzon** [kubevirt/vm-import-operator#98]
Replace it with vanilla `client.Client`

**Comment by pkliczewski** [comment]
After a bit of investigation it seems we won't be able to use the `client.Client` because we need to pass [Scheme](https://github.com/kubernetes-sigs/controller-runtime/blob/e00985b30c688f246e59400ff715e3a2331fa75f/pkg/client/client.go#L82) upon creation. We have no control over how the client is [created](https://github.com/kubernetes-sigs/controller-runtime/blob/a7c8a93c1cf395974911ef0ece977a7d27b2bf4b/pkg/manager/manager.go#L251) by `manager.Manager`. I suggest to close this as not possible. @jakub-dzon  what do you think?

**Comment by jakub-dzon** [comment]
:+1:
Closing the issue.
